/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121296-gf1d5114103-20251003"
#endif /* AVUTIL_FFVERSION_H */
